[package]
name = "emcctest"
version = "0.1.0"
authors = ["Erik Vesteraas <erik@vestera.as>"]

[dependencies.json_typegen_shared]
git = "https://github.com/evestera/json_typegen"
default-features = false
features = []

[profile.release]
opt-level = "z"
lto = true
panic = 'abort'
